### ISSUE TITLE
Finish Redesign

### ISSUE THREAD

**Issue by ghost** [relevance/tarantula#2]
[original LH ticket](http://relevance.lighthouseapp.com/projects/17868/tickets/10)

 This ticket has 0 attachment(s).

**Comment by ghost** [comment]
**Finish Redesign**

Implementation started in commit 0ea9d8b.

http://github.com/relevance/tarantula/commit/0ea9d8bd44beaabefefd6d82f280c62b6f4a87c5

A few cleanup items remain before closing out this ticket.

 by Jason Rudolph

**Comment by jasonrudolph** [comment]
Finish redesign. Closed by 598c1d8cba32b147fbe47bf4dc230ff99a08acdb.
- Replace use of images for buttons. Use vanilla
  CSS styling instead.
- Remove obsolete button image files and update
  gemspec accordingly.
- Fix problem where long test names exceed button
  width.
- Decided to always show the test result body and
  log (instead of using JavaScript to hide/show
  these sections).
